=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/gdb-target.dtd
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- The root element of a GDB target description is <target>.  -->

<!-- The osabi and compatible elements were added post GDB 6.8.  The version
     wasn't bumped, since older GDBs silently ignore unknown elements.  -->

<!ELEMENT target	(architecture?, osabi?, compatible*, feature*)>
<!ATTLIST target
	version		CDATA	#FIXED "1.0">

<!ELEMENT architecture	(#PCDATA)>

<!ELEMENT osabi	(#PCDATA)>

<!ELEMENT compatible	(#PCDATA)>

<!ELEMENT feature
	((vector | flags | struct | union )*, reg*)>
<!ATTLIST feature
	name		ID	#REQUIRED>

<!ELEMENT reg		(description*)>
<!ATTLIST reg
	name		CDATA	#REQUIRED
	bitsize		CDATA	#REQUIRED
	regnum		CDATA	#IMPLIED
	save-restore	(yes | no) 'yes'
	type		CDATA	'int'
	group		CDATA	#IMPLIED
	>

<!ELEMENT vector	EMPTY>
<!ATTLIST vector
	id		CDATA	#REQUIRED
	type		CDATA	#REQUIRED
	count		CDATA	#REQUIRED>

<!ELEMENT flags		(field+)>
<!ATTLIST flags
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT enum		(evalue+)>
<!ATTLIST enum
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT struct	(field+)>
<!ATTLIST struct
	id		CDATA	#REQUIRED
	size		CDATA	#IMPLIED>

<!ELEMENT union		(field+)>
<!ATTLIST union
	id		CDATA	#REQUIRED>

<!ELEMENT field		EMPTY>
<!ATTLIST field
	name		CDATA	#REQUIRED
	type		CDATA	#IMPLIED
	start		CDATA	#IMPLIED
	end		CDATA	#IMPLIED>

<!ELEMENT evalue	EMPTY>
<!ATTLIST evalue
	name		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ENTITY % xinclude SYSTEM "xinclude.dtd">
%xinclude;

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/arc/v1-aux.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2015-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.arc.aux">
  <flags id="status32_type" size="4">
      <field name="H"   start="0" end="0"/>
      <field name="E"   start="1" end="2"/>
      <field name="A"   start="3" end="4"/>
      <field name="AE"  start="5" end="5"/>
      <field name="DE"  start="6" end="6"/>
      <field name="U"   start="7" end="7"/>
      <field name="V"   start="8" end="8"/>
      <field name="C"   start="9" end="9"/>
      <field name="N"   start="10" end="10"/>
      <field name="Z"   start="11" end="11"/>
      <field name="L"   start="12" end="12"/>
      <field name="R"   start="13" end="13"/>
      <field name="SE"  start="14" end="14"/>
  </flags>

  <reg name="pc"       bitsize="32" type="code_ptr"/>
  <reg name="status32" bitsize="32" type="status32_type"/>
  <reg name="lp_start" bitsize="32" type="code_ptr"/>
  <reg name="lp_end"   bitsize="32" type="code_ptr"/>
  <reg name="bta"      bitsize="32" type="code_ptr"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/tic6x-core.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2010-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.tic6x.core">
  <reg name="A0" bitsize="32" type="uint32"/>
  <reg name="A1" bitsize="32" type="uint32"/>
  <reg name="A2" bitsize="32" type="uint32"/>
  <reg name="A3" bitsize="32" type="uint32"/>
  <reg name="A4" bitsize="32" type="uint32"/>
  <reg name="A5" bitsize="32" type="uint32"/>
  <reg name="A6" bitsize="32" type="uint32"/>
  <reg name="A7" bitsize="32" type="uint32"/>
  <reg name="A8" bitsize="32" type="uint32"/>
  <reg name="A9" bitsize="32" type="uint32"/>
  <reg name="A10" bitsize="32" type="uint32"/>
  <reg name="A11" bitsize="32" type="uint32"/>
  <reg name="A12" bitsize="32" type="uint32"/>
  <reg name="A13" bitsize="32" type="uint32"/>
  <reg name="A14" bitsize="32" type="uint32"/>
  <reg name="A15" bitsize="32" type="uint32"/>
  <reg name="B0" bitsize="32" type="uint32"/>
  <reg name="B1" bitsize="32" type="uint32"/>
  <reg name="B2" bitsize="32" type="uint32"/>
  <reg name="B3" bitsize="32" type="uint32"/>
  <reg name="B4" bitsize="32" type="uint32"/>
  <reg name="B5" bitsize="32" type="uint32"/>
  <reg name="B6" bitsize="32" type="uint32"/>
  <reg name="B7" bitsize="32" type="uint32"/>
  <reg name="B8" bitsize="32" type="uint32"/>
  <reg name="B9" bitsize="32" type="uint32"/>
  <reg name="B10" bitsize="32" type="uint32"/>
  <reg name="B11" bitsize="32" type="uint32"/>
  <reg name="B12" bitsize="32" type="uint32"/>
  <reg name="B13" bitsize="32" type="uint32"/>
  <reg name="B14" bitsize="32" type="uint32"/>
  <reg name="B15" bitsize="32" type="uint32"/>
  <reg name="CSR" bitsize="32" type="uint32"/>
  <reg name="PC" bitsize="32" type="code_ptr"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/power-htm-altivec.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2018-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- POWER8 Hardware Transactional Memory checkpointed VRs.  -->
<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.power.htm.altivec">
  <vector id="v4f" type="ieee_single" count="4"/>
  <vector id="v4i32" type="int32" count="4"/>
  <vector id="v8i16" type="int16" count="8"/>
  <vector id="v16i8" type="int8" count="16"/>
  <union id="vec128">
    <field name="uint128" type="uint128"/>
    <field name="v4_float" type="v4f"/>
    <field name="v4_int32" type="v4i32"/>
    <field name="v8_int16" type="v8i16"/>
    <field name="v16_int8" type="v16i8"/>
  </union>

  <reg name="cvr0" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr1" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr2" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr3" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr4" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr5" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr6" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr7" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr8" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr9" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr10" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr11" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr12" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr13" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr14" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr15" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr16" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr17" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr18" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr19" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr20" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr21" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr22" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr23" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr24" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr25" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr26" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr27" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr28" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr29" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr30" bitsize="128" type="vec128" save-restore="no"/>
  <reg name="cvr31" bitsize="128" type="vec128" save-restore="no"/>

  <reg name="cvscr" bitsize="32" save-restore="no" group="vector"/>
  <reg name="cvrsave" bitsize="32" save-restore="no" group="vector"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/powerpc-601.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- IBM POWER (pre-PowerPC) architecture, user-level view.  We only cover
     user-level SPR's.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target>
  <!-- This description is slightly different from the standard
       org.gnu.gdb.power.core, to accommodate mq.  -->
  <feature name="org.gnu.gdb.power.core">
    <reg name="r0" bitsize="32"/>
    <reg name="r1" bitsize="32"/>
    <reg name="r2" bitsize="32"/>
    <reg name="r3" bitsize="32"/>
    <reg name="r4" bitsize="32"/>
    <reg name="r5" bitsize="32"/>
    <reg name="r6" bitsize="32"/>
    <reg name="r7" bitsize="32"/>
    <reg name="r8" bitsize="32"/>
    <reg name="r9" bitsize="32"/>
    <reg name="r10" bitsize="32"/>
    <reg name="r11" bitsize="32"/>
    <reg name="r12" bitsize="32"/>
    <reg name="r13" bitsize="32"/>
    <reg name="r14" bitsize="32"/>
    <reg name="r15" bitsize="32"/>
    <reg name="r16" bitsize="32"/>
    <reg name="r17" bitsize="32"/>
    <reg name="r18" bitsize="32"/>
    <reg name="r19" bitsize="32"/>
    <reg name="r20" bitsize="32"/>
    <reg name="r21" bitsize="32"/>
    <reg name="r22" bitsize="32"/>
    <reg name="r23" bitsize="32"/>
    <reg name="r24" bitsize="32"/>
    <reg name="r25" bitsize="32"/>
    <reg name="r26" bitsize="32"/>
    <reg name="r27" bitsize="32"/>
    <reg name="r28" bitsize="32"/>
    <reg name="r29" bitsize="32"/>
    <reg name="r30" bitsize="32"/>
    <reg name="r31" bitsize="32"/>

    <reg name="pc" bitsize="32" type="code_ptr" regnum="64"/>
    <reg name="msr" bitsize="32"/>
    <reg name="cr" bitsize="32"/>
    <reg name="lr" bitsize="32" type="code_ptr"/>
    <reg name="ctr" bitsize="32"/>
    <reg name="xer" bitsize="32"/>
    <reg name="mq" bitsize="32" regnum="124"/>
  </feature>

  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="601">
    <reg name="hid0" bitsize="32"/>
    <reg name="hid1" bitsize="32"/>
    <reg name="iabr" bitsize="32"/>
    <reg name="pir" bitsize="32" regnum="123"/>
    <reg name="rtcu" bitsize="32" regnum="125"/>
    <reg name="rtcl" bitsize="32"/>
  </feature>
</target>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/rs6000.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- IBM POWER (pre-PowerPC) architecture, user-level view.  We only cover
     user-level SPR's.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target>
  <architecture>rs6000:6000</architecture>

  <!-- This description is slightly different from the standard
       org.gnu.gdb.power.core, to accommodate mq, cnd, and cnt.  -->
  <feature name="org.gnu.gdb.power.core">
    <reg name="r0" bitsize="32"/>
    <reg name="r1" bitsize="32"/>
    <reg name="r2" bitsize="32"/>
    <reg name="r3" bitsize="32"/>
    <reg name="r4" bitsize="32"/>
    <reg name="r5" bitsize="32"/>
    <reg name="r6" bitsize="32"/>
    <reg name="r7" bitsize="32"/>
    <reg name="r8" bitsize="32"/>
    <reg name="r9" bitsize="32"/>
    <reg name="r10" bitsize="32"/>
    <reg name="r11" bitsize="32"/>
    <reg name="r12" bitsize="32"/>
    <reg name="r13" bitsize="32"/>
    <reg name="r14" bitsize="32"/>
    <reg name="r15" bitsize="32"/>
    <reg name="r16" bitsize="32"/>
    <reg name="r17" bitsize="32"/>
    <reg name="r18" bitsize="32"/>
    <reg name="r19" bitsize="32"/>
    <reg name="r20" bitsize="32"/>
    <reg name="r21" bitsize="32"/>
    <reg name="r22" bitsize="32"/>
    <reg name="r23" bitsize="32"/>
    <reg name="r24" bitsize="32"/>
    <reg name="r25" bitsize="32"/>
    <reg name="r26" bitsize="32"/>
    <reg name="r27" bitsize="32"/>
    <reg name="r28" bitsize="32"/>
    <reg name="r29" bitsize="32"/>
    <reg name="r30" bitsize="32"/>
    <reg name="r31" bitsize="32"/>

    <reg name="pc" bitsize="32" type="code_ptr" regnum="64"/>
    <reg name="msr" bitsize="32"/>
    <reg name="cnd" bitsize="32"/>
    <reg name="lr" bitsize="32" type="code_ptr"/>
    <reg name="cnt" bitsize="32"/>
    <reg name="xer" bitsize="32"/>
    <reg name="mq" bitsize="32"/>
  </feature>

  <!-- This description is slightly different from the standard
       org.gnu.gdb.power.core, to accommodate historical numbering
       for fpscr.  -->
  <feature name="org.gnu.gdb.power.fpu">
    <reg name="f0" bitsize="64" type="ieee_double" regnum="32"/>
    <reg name="f1" bitsize="64" type="ieee_double"/>
    <reg name="f2" bitsize="64" type="ieee_double"/>
    <reg name="f3" bitsize="64" type="ieee_double"/>
    <reg name="f4" bitsize="64" type="ieee_double"/>
    <reg name="f5" bitsize="64" type="ieee_double"/>
    <reg name="f6" bitsize="64" type="ieee_double"/>
    <reg name="f7" bitsize="64" type="ieee_double"/>
    <reg name="f8" bitsize="64" type="ieee_double"/>
    <reg name="f9" bitsize="64" type="ieee_double"/>
    <reg name="f10" bitsize="64" type="ieee_double"/>
    <reg name="f11" bitsize="64" type="ieee_double"/>
    <reg name="f12" bitsize="64" type="ieee_double"/>
    <reg name="f13" bitsize="64" type="ieee_double"/>
    <reg name="f14" bitsize="64" type="ieee_double"/>
    <reg name="f15" bitsize="64" type="ieee_double"/>
    <reg name="f16" bitsize="64" type="ieee_double"/>
    <reg name="f17" bitsize="64" type="ieee_double"/>
    <reg name="f18" bitsize="64" type="ieee_double"/>
    <reg name="f19" bitsize="64" type="ieee_double"/>
    <reg name="f20" bitsize="64" type="ieee_double"/>
    <reg name="f21" bitsize="64" type="ieee_double"/>
    <reg name="f22" bitsize="64" type="ieee_double"/>
    <reg name="f23" bitsize="64" type="ieee_double"/>
    <reg name="f24" bitsize="64" type="ieee_double"/>
    <reg name="f25" bitsize="64" type="ieee_double"/>
    <reg name="f26" bitsize="64" type="ieee_double"/>
    <reg name="f27" bitsize="64" type="ieee_double"/>
    <reg name="f28" bitsize="64" type="ieee_double"/>
    <reg name="f29" bitsize="64" type="ieee_double"/>
    <reg name="f30" bitsize="64" type="ieee_double"/>
    <reg name="f31" bitsize="64" type="ieee_double"/>

    <reg name="fpscr" bitsize="32" group="float" regnum="71"/>
  </feature>
</target>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/powerpc-405.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2009-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target>
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>

  <feature name="405">
    <reg name="pvr" bitsize="32" regnum="87"/>
    <reg name="sprg0" bitsize="32" regnum="108"/>
    <reg name="sprg1" bitsize="32"/>
    <reg name="sprg2" bitsize="32"/>
    <reg name="sprg3" bitsize="32"/>
    <reg name="srr0" bitsize="32"/>
    <reg name="srr1" bitsize="32"/>
    <reg name="tbl" bitsize="32"/>
    <reg name="tbu" bitsize="32"/>
    <reg name="icdbdr" bitsize="32" regnum="119"/>
    <reg name="esr" bitsize="32"/>
    <reg name="dear" bitsize="32"/>
    <reg name="evpr" bitsize="32"/>
    <reg name="tsr" bitsize="32" regnum="124"/>
    <reg name="tcr" bitsize="32"/>
    <reg name="pit" bitsize="32"/>
    <reg name="srr2" bitsize="32" regnum="129"/>
    <reg name="srr3" bitsize="32"/>
    <reg name="dbsr" bitsize="32"/>
    <reg name="dbcr" bitsize="32"/>
    <reg name="iac1" bitsize="32"/>
    <reg name="iac2" bitsize="32"/>
    <reg name="dac1" bitsize="32"/>
    <reg name="dac2" bitsize="32"/>
    <reg name="dccr" bitsize="32"/>
    <reg name="iccr" bitsize="32"/>
    <reg name="zpr" bitsize="32" regnum="143"/>
    <reg name="pid" bitsize="32"/>
    <reg name="sgr" bitsize="32"/>
    <reg name="dcwr" bitsize="32"/>
    <reg name="ccr0" bitsize="32" regnum="149"/>
    <reg name="dbcr1" bitsize="32"/>
    <reg name="dvc1" bitsize="32"/>
    <reg name="dvc2" bitsize="32"/>
    <reg name="iac3" bitsize="32"/>
    <reg name="iac4" bitsize="32"/>
    <reg name="sler" bitsize="32"/>
    <reg name="sprg4" bitsize="32"/>
    <reg name="sprg5" bitsize="32"/>
    <reg name="sprg6" bitsize="32"/>
    <reg name="sprg7" bitsize="32"/>
    <reg name="su0r" bitsize="32"/>
    <reg name="usprg0" bitsize="32"/>
  </feature>
</target>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/power-oea.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- The registers (some of them, anyway) defined by the
     Operating Environment Architecture.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="OEA">
  <reg name="sr0" bitsize="32" regnum="71"/>
  <reg name="sr1" bitsize="32"/>
  <reg name="sr2" bitsize="32"/>
  <reg name="sr3" bitsize="32"/>
  <reg name="sr4" bitsize="32"/>
  <reg name="sr5" bitsize="32"/>
  <reg name="sr6" bitsize="32"/>
  <reg name="sr7" bitsize="32"/>
  <reg name="sr8" bitsize="32"/>
  <reg name="sr9" bitsize="32"/>
  <reg name="sr10" bitsize="32"/>
  <reg name="sr11" bitsize="32"/>
  <reg name="sr12" bitsize="32"/>
  <reg name="sr13" bitsize="32"/>
  <reg name="sr14" bitsize="32"/>
  <reg name="sr15" bitsize="32"/>

  <reg name="pvr" bitsize="32"/>
  <reg name="ibat0u" bitsize="32"/>
  <reg name="ibat0l" bitsize="32"/>
  <reg name="ibat1u" bitsize="32"/>
  <reg name="ibat1l" bitsize="32"/>
  <reg name="ibat2u" bitsize="32"/>
  <reg name="ibat2l" bitsize="32"/>
  <reg name="ibat3u" bitsize="32"/>
  <reg name="ibat3l" bitsize="32"/>
  <reg name="dbat0u" bitsize="32"/>
  <reg name="dbat0l" bitsize="32"/>
  <reg name="dbat1u" bitsize="32"/>
  <reg name="dbat1l" bitsize="32"/>
  <reg name="dbat2u" bitsize="32"/>
  <reg name="dbat2l" bitsize="32"/>
  <reg name="dbat3u" bitsize="32"/>
  <reg name="dbat3l" bitsize="32"/>
  <reg name="sdr1" bitsize="32"/>
  <reg name="asr" bitsize="64"/>
  <reg name="dar" bitsize="32"/>
  <reg name="dsisr" bitsize="32"/>
  <reg name="sprg0" bitsize="32"/>
  <reg name="sprg1" bitsize="32"/>
  <reg name="sprg2" bitsize="32"/>
  <reg name="sprg3" bitsize="32"/>
  <reg name="srr0" bitsize="32"/>
  <reg name="srr1" bitsize="32"/>
  <reg name="tbl" bitsize="32"/>
  <reg name="tbu" bitsize="32"/>
  <reg name="dec" bitsize="32"/>
  <reg name="dabr" bitsize="32"/>
  <reg name="ear" bitsize="32"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/powerpc-602.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target>
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="602">
    <reg name="hid0" bitsize="32"/>
    <reg name="hid1" bitsize="32"/>
    <reg name="iabr" bitsize="32"/>
    <reg name="tcr" bitsize="32" regnum="124"/>
    <reg name="ibr" bitsize="32"/>
    <reg name="esasrr" bitsize="32"/>
    <reg name="sebr" bitsize="32"/>
    <reg name="ser" bitsize="32"/>
    <reg name="sp" bitsize="32"/>
    <reg name="lt" bitsize="32"/>
  </feature>
</target>
