=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/gdb-target.dtd
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- The root element of a GDB target description is <target>.  -->

<!-- The osabi and compatible elements were added post GDB 6.8.  The version
     wasn't bumped, since older GDBs silently ignore unknown elements.  -->

<!ELEMENT target	(architecture?, osabi?, compatible*, feature*)>
<!ATTLIST target
	version		CDATA	#FIXED "1.0">

<!ELEMENT architecture	(#PCDATA)>

<!ELEMENT osabi	(#PCDATA)>

<!ELEMENT compatible	(#PCDATA)>

<!ELEMENT feature
	((vector | flags | struct | union )*, reg*)>
<!ATTLIST feature
	name		ID	#REQUIRED>

<!ELEMENT reg		(description*)>
<!ATTLIST reg
	name		CDATA	#REQUIRED
	bitsize		CDATA	#REQUIRED
	regnum		CDATA	#IMPLIED
	save-restore	(yes | no) 'yes'
	type		CDATA	'int'
	group		CDATA	#IMPLIED
	>

<!ELEMENT vector	EMPTY>
<!ATTLIST vector
	id		CDATA	#REQUIRED
	type		CDATA	#REQUIRED
	count		CDATA	#REQUIRED>

<!ELEMENT flags		(field+)>
<!ATTLIST flags
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT enum		(evalue+)>
<!ATTLIST enum
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT struct	(field+)>
<!ATTLIST struct
	id		CDATA	#REQUIRED
	size		CDATA	#IMPLIED>

<!ELEMENT union		(field+)>
<!ATTLIST union
	id		CDATA	#REQUIRED>

<!ELEMENT field		EMPTY>
<!ATTLIST field
	name		CDATA	#REQUIRED
	type		CDATA	#IMPLIED
	start		CDATA	#IMPLIED
	end		CDATA	#IMPLIED>

<!ELEMENT evalue	EMPTY>
<!ATTLIST evalue
	name		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ENTITY % xinclude SYSTEM "xinclude.dtd">
%xinclude;

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/power-htm-vsx.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2018-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- POWER8 Hardware Transactional Memory checkpointed upper VSRs.  -->
<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.power.htm.vsx">
  <reg name="cvs0h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs1h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs2h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs3h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs4h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs5h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs6h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs7h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs8h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs9h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs10h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs11h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs12h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs13h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs14h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs15h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs16h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs17h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs18h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs19h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs20h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs21h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs22h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs23h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs24h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs25h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs26h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs27h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs28h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs29h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs30h" bitsize="64" type="uint64" save-restore="no"/>
  <reg name="cvs31h" bitsize="64" type="uint64" save-restore="no"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/powerpc-603.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- PowerPC 603 or 603e.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target>
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="603">
    <reg name="hid0" bitsize="32"/>
    <reg name="hid1" bitsize="32"/>
    <reg name="iabr" bitsize="32"/>
    <reg name="dmiss" bitsize="32" regnum="124"/>
    <reg name="dcmp" bitsize="32"/>
    <reg name="hash1" bitsize="32"/>
    <reg name="hash2" bitsize="32"/>
    <reg name="imiss" bitsize="32"/>
    <reg name="icmp" bitsize="32"/>
    <reg name="rpa" bitsize="32"/>
  </feature>
</target>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/power-htm-core.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2018-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- POWER8 Hardware Transactional Memory checkpointed GPRs.  -->
<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.power.htm.core">
  <reg name="cr0" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr1" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr2" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr3" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr4" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr5" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr6" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr7" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr8" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr9" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr10" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr11" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr12" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr13" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr14" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr15" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr16" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr17" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr18" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr19" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr20" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr21" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr22" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr23" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr24" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr25" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr26" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr27" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr28" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr29" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr30" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cr31" bitsize="32" type="uint32" save-restore="no"/>

  <reg name="ccr" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="cxer" bitsize="32" type="uint32" save-restore="no"/>
  <reg name="clr" bitsize="32" type="code_ptr" save-restore="no"/>
  <reg name="cctr" bitsize="32" type="uint32" save-restore="no"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/tic6x-gp.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2010-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.tic6x.gp">
  <reg name="A16" bitsize="32" type="uint32"/>
  <reg name="A17" bitsize="32" type="uint32"/>
  <reg name="A18" bitsize="32" type="uint32"/>
  <reg name="A19" bitsize="32" type="uint32"/>
  <reg name="A20" bitsize="32" type="uint32"/>
  <reg name="A21" bitsize="32" type="uint32"/>
  <reg name="A22" bitsize="32" type="uint32"/>
  <reg name="A23" bitsize="32" type="uint32"/>
  <reg name="A24" bitsize="32" type="uint32"/>
  <reg name="A25" bitsize="32" type="uint32"/>
  <reg name="A26" bitsize="32" type="uint32"/>
  <reg name="A27" bitsize="32" type="uint32"/>
  <reg name="A28" bitsize="32" type="uint32"/>
  <reg name="A29" bitsize="32" type="uint32"/>
  <reg name="A30" bitsize="32" type="uint32"/>
  <reg name="A31" bitsize="32" type="uint32"/>
  <reg name="B16" bitsize="32" type="uint32"/>
  <reg name="B17" bitsize="32" type="uint32"/>
  <reg name="B18" bitsize="32" type="uint32"/>
  <reg name="B19" bitsize="32" type="uint32"/>
  <reg name="B20" bitsize="32" type="uint32"/>
  <reg name="B21" bitsize="32" type="uint32"/>
  <reg name="B22" bitsize="32" type="uint32"/>
  <reg name="B23" bitsize="32" type="uint32"/>
  <reg name="B24" bitsize="32" type="uint32"/>
  <reg name="B25" bitsize="32" type="uint32"/>
  <reg name="B26" bitsize="32" type="uint32"/>
  <reg name="B27" bitsize="32" type="uint32"/>
  <reg name="B28" bitsize="32" type="uint32"/>
  <reg name="B29" bitsize="32" type="uint32"/>
  <reg name="B30" bitsize="32" type="uint32"/>
  <reg name="B31" bitsize="32" type="uint32"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/mips64-dsp.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2012-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.mips.dsp">
  <reg name="hi1" bitsize="64" regnum="72"/>
  <reg name="lo1" bitsize="64" regnum="73"/>
  <reg name="hi2" bitsize="64" regnum="74"/>
  <reg name="lo2" bitsize="64" regnum="75"/>
  <reg name="hi3" bitsize="64" regnum="76"/>
  <reg name="lo3" bitsize="64" regnum="77"/>

  <reg name="dspctl" bitsize="32" regnum="78"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/cskyv2-linux.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2022-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.csky.abiv2">
  <reg name="r0"  bitsize="32" regnum="0"/>
  <reg name="r1"  bitsize="32"/>
  <reg name="r2"  bitsize="32"/>
  <reg name="r3"  bitsize="32"/>
  <reg name="r4"  bitsize="32"/>
  <reg name="r5"  bitsize="32"/>
  <reg name="r6"  bitsize="32"/>
  <reg name="r7"  bitsize="32"/>
  <reg name="r8"  bitsize="32"/>
  <reg name="r9"  bitsize="32"/>
  <reg name="r10" bitsize="32"/>
  <reg name="r11" bitsize="32"/>
  <reg name="r12" bitsize="32"/>
  <reg name="r13" bitsize="32"/>
  <reg name="r14" bitsize="32" type="data_ptr"/>
  <reg name="r15" bitsize="32"/>
  <reg name="r16" bitsize="32"/>
  <reg name="r17" bitsize="32"/>
  <reg name="r18" bitsize="32"/>
  <reg name="r19" bitsize="32"/>
  <reg name="r20" bitsize="32"/>
  <reg name="r21" bitsize="32"/>
  <reg name="r22" bitsize="32"/>
  <reg name="r23" bitsize="32"/>
  <reg name="r24" bitsize="32"/>
  <reg name="r25" bitsize="32"/>
  <reg name="r26" bitsize="32"/>
  <reg name="r27" bitsize="32"/>
  <reg name="r28" bitsize="32"/>
  <reg name="r29" bitsize="32"/>
  <reg name="r30" bitsize="32"/>
  <reg name="r31" bitsize="32"/>

  <reg name="hi" bitsize="32" regnum="36"/>
  <reg name="lo" bitsize="32"/>

  <reg name="fr0"  bitsize="64" type="ieee_double" regnum="40"/>
  <reg name="fr1"  bitsize="64" type="ieee_double"/>
  <reg name="fr2"  bitsize="64" type="ieee_double"/>
  <reg name="fr3"  bitsize="64" type="ieee_double"/>
  <reg name="fr4"  bitsize="64" type="ieee_double"/>
  <reg name="fr5"  bitsize="64" type="ieee_double"/>
  <reg name="fr6"  bitsize="64" type="ieee_double"/>
  <reg name="fr7"  bitsize="64" type="ieee_double"/>
  <reg name="fr8"  bitsize="64" type="ieee_double"/>
  <reg name="fr9"  bitsize="64" type="ieee_double"/>
  <reg name="fr10" bitsize="64" type="ieee_double"/>
  <reg name="fr11" bitsize="64" type="ieee_double"/>
  <reg name="fr12" bitsize="64" type="ieee_double"/>
  <reg name="fr13" bitsize="64" type="ieee_double"/>
  <reg name="fr14" bitsize="64" type="ieee_double"/>
  <reg name="fr15" bitsize="64" type="ieee_double"/>

  <vector id="v4f"   type="ieee_single" count="4"/>
  <vector id="v2d"   type="ieee_double" count="2"/>
  <vector id="v16i8" type="int8" count="16"/>
  <vector id="v8i16" type="int16" count="8"/>
  <vector id="v4i32" type="int32" count="4"/>
  <vector id="v2i64" type="int64" count="2"/>
  <union id="vec128">
    <field name="v4_float"  type="v4f"/>
    <field name="v2_double" type="v2d"/>
    <field name="v16_int8"  type="v16i8"/>
    <field name="v8_int16"  type="v8i16"/>
    <field name="v4_int32"  type="v4i32"/>
    <field name="v2_int64"  type="v2i64"/>
    <field name="uint128"   type="uint128"/>
  </union>
  <reg name="vr0"  bitsize="128" type="vec128" regnum="56"/>
  <reg name="vr1"  bitsize="128" type="vec128"/>
  <reg name="vr2"  bitsize="128" type="vec128"/>
  <reg name="vr3"  bitsize="128" type="vec128"/>
  <reg name="vr4"  bitsize="128" type="vec128"/>
  <reg name="vr5"  bitsize="128" type="vec128"/>
  <reg name="vr6"  bitsize="128" type="vec128"/>
  <reg name="vr7"  bitsize="128" type="vec128"/>
  <reg name="vr8"  bitsize="128" type="vec128"/>
  <reg name="vr9"  bitsize="128" type="vec128"/>
  <reg name="vr10" bitsize="128" type="vec128"/>
  <reg name="vr11" bitsize="128" type="vec128"/>
  <reg name="vr12" bitsize="128" type="vec128"/>
  <reg name="vr13" bitsize="128" type="vec128"/>
  <reg name="vr14" bitsize="128" type="vec128"/>
  <reg name="vr15" bitsize="128" type="vec128"/>

  <reg name="pc"   bitsize="32" type="code_ptr" regnum="72"/>
  <reg name="psr"  bitsize="32" regnum="89"/>

  <reg name="fid"  bitsize="32" regnum="121"/>
  <reg name="fcr"  bitsize="32"/>
  <reg name="fesr" bitsize="32"/>
  <reg name="usp"  bitsize="32" regnum="127"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/powerpc-750.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- PowerPC 750 or 740.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target>
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="750">
    <reg name="hid0" bitsize="32"/>
    <reg name="hid1" bitsize="32"/>
    <reg name="iabr" bitsize="32"/>
    <reg name="ummcr0" bitsize="32" regnum="124"/>
    <reg name="upmc1" bitsize="32"/>
    <reg name="upmc2" bitsize="32"/>
    <reg name="usia" bitsize="32"/>
    <reg name="ummcr1" bitsize="32"/>
    <reg name="upmc3" bitsize="32"/>
    <reg name="upmc4" bitsize="32"/>
    <reg name="mmcr0" bitsize="32"/>
    <reg name="pmc1" bitsize="32"/>
    <reg name="pmc2" bitsize="32"/>
    <reg name="sia" bitsize="32"/>
    <reg name="mmcr1" bitsize="32"/>
    <reg name="pmc3" bitsize="32"/>
    <reg name="pmc4" bitsize="32"/>
    <reg name="l2cr" bitsize="32"/>
    <reg name="ictc" bitsize="32"/>
    <reg name="thrm1" bitsize="32"/>
    <reg name="thrm2" bitsize="32"/>
    <reg name="thrm3" bitsize="32"/>
  </feature>
</target>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/s390-core64.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2010-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.s390.core">
  <reg name="pswm" bitsize="32" type="uint32" group="psw"/>
  <reg name="pswa" bitsize="32" type="uint32" group="psw"/>
  <reg name="r0h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r0l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r1h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r1l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r2h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r2l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r3h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r3l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r4h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r4l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r5h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r5l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r6h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r6l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r7h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r7l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r8h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r8l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r9h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r9l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r10h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r10l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r11h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r11l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r12h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r12l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r13h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r13l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r14h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r14l" bitsize="32" type="uint32" group="lower"/>
  <reg name="r15h" bitsize="32" type="uint32" group="upper"/>
  <reg name="r15l" bitsize="32" type="uint32" group="lower"/>
</feature>
