=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/gdb-target.dtd
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- The root element of a GDB target description is <target>.  -->

<!-- The osabi and compatible elements were added post GDB 6.8.  The version
     wasn't bumped, since older GDBs silently ignore unknown elements.  -->

<!ELEMENT target	(architecture?, osabi?, compatible*, feature*)>
<!ATTLIST target
	version		CDATA	#FIXED "1.0">

<!ELEMENT architecture	(#PCDATA)>

<!ELEMENT osabi	(#PCDATA)>

<!ELEMENT compatible	(#PCDATA)>

<!ELEMENT feature
	((vector | flags | struct | union )*, reg*)>
<!ATTLIST feature
	name		ID	#REQUIRED>

<!ELEMENT reg		(description*)>
<!ATTLIST reg
	name		CDATA	#REQUIRED
	bitsize		CDATA	#REQUIRED
	regnum		CDATA	#IMPLIED
	save-restore	(yes | no) 'yes'
	type		CDATA	'int'
	group		CDATA	#IMPLIED
	>

<!ELEMENT vector	EMPTY>
<!ATTLIST vector
	id		CDATA	#REQUIRED
	type		CDATA	#REQUIRED
	count		CDATA	#REQUIRED>

<!ELEMENT flags		(field+)>
<!ATTLIST flags
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT enum		(evalue+)>
<!ATTLIST enum
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT struct	(field+)>
<!ATTLIST struct
	id		CDATA	#REQUIRED
	size		CDATA	#IMPLIED>

<!ELEMENT union		(field+)>
<!ATTLIST union
	id		CDATA	#REQUIRED>

<!ELEMENT field		EMPTY>
<!ATTLIST field
	name		CDATA	#REQUIRED
	type		CDATA	#IMPLIED
	start		CDATA	#IMPLIED
	end		CDATA	#IMPLIED>

<!ELEMENT evalue	EMPTY>
<!ATTLIST evalue
	name		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ENTITY % xinclude SYSTEM "xinclude.dtd">
%xinclude;

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/z80-cpu.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2020-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.z80.cpu">
  <flags id="af_flags" size="2">
    <field name="C" start="0" end="0"/>
    <field name="N" start="1" end="1"/>
    <field name="P/V" start="2" end="2"/>
    <field name="F3" start="3" end="3"/>
    <field name="H" start="4" end="4"/>
    <field name="F5" start="5" end="5"/>
    <field name="Z" start="6" end="6"/>
    <field name="S" start="7" end="7"/>
  </flags>
  <reg name="af" bitsize="16" type="af_flags"/>
  <reg name="bc" bitsize="16" type="uint16"/>
  <reg name="de" bitsize="16" type="data_ptr"/>
  <reg name="hl" bitsize="16" type="data_ptr"/>
  <reg name="sp" bitsize="16" type="data_ptr" />
  <reg name="pc" bitsize="32" type="code_ptr" />
  <reg name="ix" bitsize="16" type="data_ptr"/>
  <reg name="iy" bitsize="16" type="data_ptr"/>
  <reg name="af'" bitsize="16" type="af_flags"/>
  <reg name="bc'" bitsize="16" type="uint16"/>
  <reg name="de'" bitsize="16" type="data_ptr"/>
  <reg name="hl'" bitsize="16" type="data_ptr"/>
  <reg name="ir" bitsize="16" type="uint16"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/nios2-cpu.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2012-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.nios2.cpu">
  <reg name="zero" bitsize="32" type="uint32"/>
  <reg name="at" bitsize="32" type="uint32"/>
  <reg name="r2" bitsize="32" type="uint32"/>
  <reg name="r3" bitsize="32" type="uint32"/>
  <reg name="r4" bitsize="32" type="uint32"/>
  <reg name="r5" bitsize="32" type="uint32"/>
  <reg name="r6" bitsize="32" type="uint32"/>
  <reg name="r7" bitsize="32" type="uint32"/>
  <reg name="r8" bitsize="32" type="uint32"/>
  <reg name="r9" bitsize="32" type="uint32"/>
  <reg name="r10" bitsize="32" type="uint32"/>
  <reg name="r11" bitsize="32" type="uint32"/>
  <reg name="r12" bitsize="32" type="uint32"/>
  <reg name="r13" bitsize="32" type="uint32"/>
  <reg name="r14" bitsize="32" type="uint32"/>
  <reg name="r15" bitsize="32" type="uint32"/>
  <reg name="r16" bitsize="32" type="uint32"/>
  <reg name="r17" bitsize="32" type="uint32"/>
  <reg name="r18" bitsize="32" type="uint32"/>
  <reg name="r19" bitsize="32" type="uint32"/>
  <reg name="r20" bitsize="32" type="uint32"/>
  <reg name="r21" bitsize="32" type="uint32"/>
  <reg name="r22" bitsize="32" type="uint32"/>
  <reg name="r23" bitsize="32" type="uint32"/>
  <reg name="et" bitsize="32" type="uint32"/>
  <reg name="bt" bitsize="32" type="uint32"/>
  <reg name="gp" bitsize="32" type="data_ptr"/>
  <reg name="sp" bitsize="32" type="data_ptr"/>
  <reg name="fp" bitsize="32" type="data_ptr"/>
  <reg name="ea" bitsize="32" type="code_ptr"/>
  <reg name="sstatus" bitsize="32" type="uint32"/>
  <reg name="ra" bitsize="32" type="code_ptr"/>
  <reg name="pc" bitsize="32" type="code_ptr"/>
  <reg name="status" bitsize="32" type="uint32"/>
  <reg name="estatus" bitsize="32" type="uint32"/>
  <reg name="bstatus" bitsize="32" type="uint32"/>
  <reg name="ienable" bitsize="32" type="uint32"/>
  <reg name="ipending" bitsize="32" type="uint32"/>
  <reg name="cpuid" bitsize="32" type="uint32"/>
  <reg name="ctl6" bitsize="32" type="uint32"/>
  <reg name="exception" bitsize="32" type="uint32"/>
  <reg name="pteaddr" bitsize="32" type="uint32"/>
  <reg name="tlbacc" bitsize="32" type="uint32"/>
  <reg name="tlbmisc" bitsize="32" type="uint32"/>
  <reg name="eccinj" bitsize="32" type="uint32"/>
  <reg name="badaddr" bitsize="32" type="uint32"/>
  <reg name="config" bitsize="32" type="uint32"/>
  <reg name="mpubase" bitsize="32" type="uint32"/>
  <reg name="mpuacc" bitsize="32" type="uint32"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/nds32-core.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2013-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.nds32.core">
  <reg name="r0" bitsize="32" regnum="0"/>
  <reg name="r1" bitsize="32"/>
  <reg name="r2" bitsize="32"/>
  <reg name="r3" bitsize="32"/>
  <reg name="r4" bitsize="32"/>
  <reg name="r5" bitsize="32"/>
  <reg name="r6" bitsize="32"/>
  <reg name="r7" bitsize="32"/>
  <reg name="r8" bitsize="32"/>
  <reg name="r9" bitsize="32"/>
  <reg name="r10" bitsize="32"/>
  <reg name="r11" bitsize="32"/>
  <reg name="r12" bitsize="32"/>
  <reg name="r13" bitsize="32"/>
  <reg name="r14" bitsize="32"/>
  <reg name="r15" bitsize="32"/>
  <reg name="r16" bitsize="32"/>
  <reg name="r17" bitsize="32"/>
  <reg name="r18" bitsize="32"/>
  <reg name="r19" bitsize="32"/>
  <reg name="r20" bitsize="32"/>
  <reg name="r21" bitsize="32"/>
  <reg name="r22" bitsize="32"/>
  <reg name="r23" bitsize="32"/>
  <reg name="r24" bitsize="32"/>
  <reg name="r25" bitsize="32"/>
  <reg name="r26" bitsize="32"/>
  <reg name="r27" bitsize="32"/>
  <reg name="fp" bitsize="32" type="data_ptr"/>
  <reg name="gp" bitsize="32" type="data_ptr"/>
  <reg name="lp" bitsize="32" type="code_ptr"/>
  <reg name="sp" bitsize="32" type="data_ptr"/>

  <reg name="pc" bitsize="32" type="code_ptr"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/riscv/rv32e-xregs.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2018-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- Register numbers are hard-coded in order to maintain backward
     compatibility with older versions of tools that didn't use xml
     register descriptions.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.riscv.cpu">
  <reg name="zero" bitsize="32" type="int" regnum="0"/>
  <reg name="ra" bitsize="32" type="code_ptr"/>
  <reg name="sp" bitsize="32" type="data_ptr"/>
  <reg name="gp" bitsize="32" type="data_ptr"/>
  <reg name="tp" bitsize="32" type="data_ptr"/>
  <reg name="t0" bitsize="32" type="int"/>
  <reg name="t1" bitsize="32" type="int"/>
  <reg name="t2" bitsize="32" type="int"/>
  <reg name="fp" bitsize="32" type="data_ptr"/>
  <reg name="s1" bitsize="32" type="int"/>
  <reg name="a0" bitsize="32" type="int"/>
  <reg name="a1" bitsize="32" type="int"/>
  <reg name="a2" bitsize="32" type="int"/>
  <reg name="a3" bitsize="32" type="int"/>
  <reg name="a4" bitsize="32" type="int"/>
  <reg name="a5" bitsize="32" type="int"/>
  <reg name="pc" bitsize="32" type="code_ptr"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/rs6000/power-htm-fpu.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2018-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- POWER8 Hardware Transactional Memory checkpointed FPRs.  -->
<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.power.htm.fpu">
  <reg name="cf0" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf1" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf2" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf3" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf4" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf5" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf6" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf7" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf8" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf9" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf10" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf11" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf12" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf13" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf14" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf15" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf16" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf17" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf18" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf19" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf20" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf21" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf22" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf23" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf24" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf25" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf26" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf27" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf28" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf29" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf30" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cf31" bitsize="64" type="ieee_double" save-restore="no"/>
  <reg name="cfpscr" bitsize="64" type="uint64" group="float"
       save-restore="no"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/testsuite/gdb.arch/arc-tdesc-cpu.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2017-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target>
  <architecture>arc:HS</architecture>

  <feature name="org.gnu.gdb.arc.core">
    <reg name="r0"  bitsize="32"/>
    <reg name="r1"  bitsize="32"/>
    <reg name="r2"  bitsize="32"/>
    <reg name="r3"  bitsize="32"/>
    <reg name="r4"  bitsize="32"/>
    <reg name="r5"  bitsize="32"/>
    <reg name="r6"  bitsize="32"/>
    <reg name="r7"  bitsize="32"/>
    <reg name="r8"  bitsize="32"/>
    <reg name="r9"  bitsize="32"/>
    <reg name="r10" bitsize="32"/>
    <reg name="r11" bitsize="32"/>
    <reg name="r12" bitsize="32"/>
    <reg name="r13" bitsize="32"/>
    <reg name="r14" bitsize="32"/>
    <reg name="r15" bitsize="32"/>
    <reg name="r16" bitsize="32"/>
    <reg name="r17" bitsize="32"/>
    <reg name="r18" bitsize="32"/>
    <reg name="r19" bitsize="32"/>
    <reg name="r20" bitsize="32"/>
    <reg name="r21" bitsize="32"/>
    <reg name="r22" bitsize="32"/>
    <reg name="r23" bitsize="32"/>
    <reg name="r24" bitsize="32"/>
    <reg name="r25" bitsize="32"/>
    <reg name="gp"  bitsize="32"/>
    <reg name="fp"  bitsize="32"/>
    <reg name="sp"  bitsize="32"/>
    <reg name="ilink" bitsize="32"/>
    <reg name="r30"   bitsize="32"/>
    <reg name="blink" bitsize="32"/>
    <reg name="lp_count" bitsize="32"/>
    <reg name="pcl" bitsize="32"/>
  </feature>

  <feature name="org.gnu.gdb.arc.aux">
    <reg name="pc"       bitsize="32"/>
    <reg name="status32" bitsize="32"/>
  </feature>
</target>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/features/s390-tdb.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2010-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.s390.tdb">
  <reg name="tdb0" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tac" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tct" bitsize="64" type="uint64" group="tdb"/>
  <reg name="atia" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr0" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr1" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr2" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr3" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr4" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr5" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr6" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr7" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr8" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr9" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr10" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr11" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr12" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr13" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr14" bitsize="64" type="uint64" group="tdb"/>
  <reg name="tr15" bitsize="64" type="uint64" group="tdb"/>
</feature>

=== riscv-collab/riscv-gnu-toolchain/binutils/gdb/testsuite/gdb.xml/maint_print_struct.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2010-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<target>
<feature name="test">

  <struct id="two_fielded">
       <field name="field1" type="data_ptr"/>
       <field name="field2" type="data_ptr"/>
  </struct>

  <struct id="bitfield" size="8">
    <field name="field0" start="0" end="0"/>
    <field name="field1" start="24" end="63"/>
    <field name="field2" start="16" end="24"/>
  </struct>

  <reg name="bad_reg1" bitsize="128" type="two_fielded"/>
  <reg name="bad_reg2" bitsize="64"  type="bitfield"/>
</feature>
</target>
